// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DiabetesPredictor.Web
{
    public partial class Characteristics
    {
        public int Id { get; set; }
        public int Pregnancies { get; set; }
        public int Glucose { get; set; }
        public int BloodPressure { get; set; }
        public int SkinThickness { get; set; }
        public int Insulin { get; set; }
        public double Bmi { get; set; }
        public double DiabetesPedigreeFunction { get; set; }
        public int Age { get; set; }
        public string UserId { get; set; }
    }
}